### ISSUE TITLE
Replace the DashExpenses with DashBudget

### ISSUE THREAD

**Issue by Sean-RD-Higgins** [Sean-RD-Higgins/ExpensesWebApplication#21]
There are numerous places where it is references DashExpenses. We are changing the name to DashBudget and we don't want to confuse users.

- Change the name in all the places.
- Remove any TODOs related to this work within the files. 
- Create a feature branch off of develop in git for this work.
- You can use the Development panel on the right to create and link the branch and pull request.

**Comment by Abdulrahman295** [comment]
Hello. Can I work on this issue?
